=== archMcMilan/Project3/src/xml/MedicineScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="medicine" type="drugsType"/>
    <xs:complexType name="drugsType">
        <xs:sequence>
            <xs:element name="drug" type="drugType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="drugType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="pharm" type="xs:string"/>
            <xs:element name="group" type="groupType"/>
            <xs:element name="analogs" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="versions" type="versionsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="antibiotics"/>
            <xs:enumeration value="analgesics"/>
            <xs:enumeration value="vitamins"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="analogsType">
        <xs:sequence>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="versionsType">
        <xs:sequence>
            <xs:element name="consistency" type="consistencyType"/>
            <xs:element name="certificate" type="certificateType"/>
            <xs:element name="package" type="packageType"/>
            <xs:element name="dosage" type="dosageType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="consistencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tablets"/>
            <xs:enumeration value="capsules"/>
            <xs:enumeration value="powders"/>
            <xs:enumeration value="drops"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="certificateType">
        <xs:sequence>
            <xs:element name="number">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="10000000"/>
                        <xs:maxInclusive value="99999999"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="issueDate" type="myDate"/>
            <xs:element name="expiryDate" type="myDate"/>
            <xs:element name="organization" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="packageType">
        <xs:sequence>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="amount" type="xs:positiveInteger"/>
            <xs:element name="price" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dosageType">
        <xs:sequence>
            <xs:element name="drugDosage" type="xs:integer"/>
            <xs:element name="period" type="xs:long"/>
        </xs:sequence>
        <xs:attribute name="units" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ml"/>
                    <xs:enumeration value="pcs"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="myDate">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}[\\.][0-9]{2}[\\.][0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== archMcMilan/Project3/src/xml/Medicine.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="MedicineScheme.xsd">
    <drug id="d1">
        <name>Analginum</name>
        <pharm>Bayern</pharm>
        <group>analgesics</group>
        <analogs>Aspirin</analogs>
        <analogs>Berlipril</analogs>
        <versions>
            <consistency>tablets</consistency>
            <certificate>
                <number>11112233</number>
                <issueDate>22.05.2016</issueDate>
                <expiryDate>22.06.2016</expiryDate>
                <organization>Darnitsa</organization>
            </certificate>
            <package>
                <type>box</type>
                <amount>120</amount>
                <price>5000</price>
            </package>
            <dosage units="pcs">
                <drugDosage>2</drugDosage>
                <period>50000</period>
            </dosage>
        </versions>
    </drug>
    <drug id="d2">
        <name>Aspirinum</name>
        <pharm>Bayern</pharm>
        <group>analgesics</group>
        <analogs>Analginum</analogs>
        <versions>
            <consistency>tablets</consistency>
            <certificate>
                <number>19112237</number>
                <issueDate>01.05.2016</issueDate>
                <expiryDate>01.07.2016</expiryDate>
                <organization>Darnitsa</organization>
            </certificate>
            <package>
                <type>box</type>
                <amount>90</amount>
                <price>12000</price>
            </package>
            <dosage units="pcs">
                <drugDosage>1</drugDosage>
                <period>40000</period>
            </dosage>
        </versions>
    </drug>

</medicine>
